/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./*/index.html",
    "./js/**/*.js",
    "./partials/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        background: "#ffffff",
        "surface-tint": "#062655",
        "on-secondary-fixed": "#001b3c",
        surface: "#ffffff",
        "tertiary-fixed": "#dbe8f7",
        "secondary-fixed-dim": "#a9c9ef",
        "on-primary-container": "#062655",
        error: "#ba1a1a",
        "primary-fixed-dim": "#dea900",
        "on-primary-fixed-variant": "#062655",
        "on-secondary-fixed-variant": "#0b3a73",
        primary: "#062655",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#344962",
        "on-background": "#061a36",
        "on-tertiary-fixed-variant": "#233853",
        "on-error": "#ffffff",
        tertiary: "#536a86",
        "surface-container-highest": "#d6e5f7",
        "secondary-fixed": "#d7e8ff",
        "inverse-on-surface": "#f5f9ff",
        "on-surface-variant": "#43556f",
        "on-surface": "#061a36",
        "on-secondary": "#ffffff",
        "tertiary-container": "#dbe8f7",
        "surface-container": "#eff5ff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#c5dcf7",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4eefb",
        "surface-container-high": "#e4eefb",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#0e1d29",
        "on-primary-fixed": "#061a36",
        "primary-container": "#fec100",
        "surface-bright": "#ffffff",
        "primary-fixed": "#ffd866",
        secondary: "#0b4a8b",
        "inverse-primary": "#fec100",
        "surface-container-low": "#f7faff",
        "on-secondary-container": "#062655",
        "on-error-container": "#93000a",
        "surface-dim": "#edf3fb",
        "outline-variant": "#b8c8dc",
        "tertiary-fixed-dim": "#b9cbe0",
        outline: "#657996",
        "inverse-surface": "#062655",
      },
      fontFamily: {
        headline: ["Space Grotesk", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      maxWidth: {
        xl: "30rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
