/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./*/index.html",
    "./js/**/*.js",
    "./partials/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        "surface-tint": "#725c00",
        "on-secondary-fixed": "#001b3c",
        surface: "#fcf9f8",
        "tertiary-fixed": "#d4e4f5",
        "secondary-fixed-dim": "#a8c8ff",
        "on-primary-container": "#6f5a00",
        error: "#ba1a1a",
        "primary-fixed-dim": "#edc200",
        "on-primary-fixed-variant": "#564500",
        "on-secondary-fixed-variant": "#034689",
        primary: "#725c00",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#4f5e6c",
        "on-background": "#1b1c1c",
        "on-tertiary-fixed-variant": "#394856",
        "on-error": "#ffffff",
        tertiary: "#51606e",
        "surface-container-highest": "#e5e2e1",
        "secondary-fixed": "#d6e3ff",
        "inverse-on-surface": "#f3f0ef",
        "on-surface-variant": "#4d4632",
        "on-surface": "#1b1c1c",
        "on-secondary": "#ffffff",
        "tertiary-container": "#c7d7e8",
        "surface-container": "#f0eded",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#87b4ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "surface-container-high": "#eae7e7",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#0e1d29",
        "on-primary-fixed": "#231b00",
        "primary-container": "#ffd100",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#ffe07f",
        secondary: "#2c5ea3",
        "inverse-primary": "#edc200",
        "surface-container-low": "#f6f3f2",
        "on-secondary-container": "#004588",
        "on-error-container": "#93000a",
        "surface-dim": "#dcd9d9",
        "outline-variant": "#d1c6ab",
        "tertiary-fixed-dim": "#b9c8d9",
        outline: "#7f765f",
        "inverse-surface": "#303030",
      },
      fontFamily: {
        headline: ["Space Grotesk", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      maxWidth: {
        xl: "30rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
